apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtp-translate-bot
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtp-translate-bot
  template:
    metadata:
      labels:
        app: gtp-translate-bot
    spec:
      containers:
        - name: gtp-translate-bot
          image: alifbank/gpt-translator-service:bot-3a3332be5a7c03a3fd8eeb54cf6b21b3704211d6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000  
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: gtp-translate-svc-env
      imagePullSecrets:
        - name: dockercred
