apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtp-translate-bot
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtp-translate-bot
  template:
    metadata:
      labels:
        app: gtp-translate-bot
    spec:
      containers:
        - name: gtp-translate-bot
          image: alifbank/gpt-translator-service:75609c9651fab332c6b50075df787a66e03c6231
          imagePullPolicy: Always
          ports:
            - containerPort: 8000  
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: gtp-translate-svc-env
      imagePullSecrets:
        - name: dockercred
