apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtp-translate
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtp-translate
  template:
    metadata:
      labels:
        app: gtp-translate
    spec:
      containers:
        - name: gtp-translate
          image: alifbank/gpt-translator-service:bef644520dc88202e81352fd1138ec18c8011f17
          imagePullPolicy: Always
          ports:
            - containerPort: 8001  
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: gtp-translate-svc-env
      imagePullSecrets:
        - name: dockercred
