apiVersion: v1
kind: Service
metadata:
  name: gtp-translate-scoring
  namespace: ml
spec:
  ports:
    - port: 80
      name: gtp-translate-scoring
      protocol: TCP
      targetPort: 80
  selector:
    app: gtp-translate